---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgAckaoAUxYC0U2Q8bQTCEBf38EieGbgbhMEHa6d5Nbq6ne5gLGql/PzlQOTXugLiYlj2O3zJ1+FYKEvaiB84Ss4kGAiBq735975Z9s0qDqZMuL7HjsHHBWBLEV1OymxnyDq043TdOcBjZHv2xtGtSIlFHJ1fzpL3qvpSxhVgfVPzIR/26osR4mTaUMaUMqnQ4WxWUgDBYgzPsfU+yjEv5xfsG0YDsVCJfzDmH0MMgkbm1PUrXAg3VYExQzUMyN/vBYM0bUrlkdaumEJuPqlbLhxoqCZtdfAh+VDyBz5S29CY/q/b1o960VPXsJeorfYiBkNQOA23XToFEXqyepHbaG000kAj+aErqIfAS7T6wMqoEw8Ksk+iRIKPIfvQS2zSGOFHGL8wXmbKfM4yEG+24C7BZIJQnIooi6CLHfEpYISqf181JrWcclsETiU+mzrY+S9e88tVNMomi2uCiiRMwoQfnXpVgh9DsqDfO1E7V7pvoIB21Y/k7KVDATeFjiAasfIwwNfeZjzt2Ju/FGZPOWoTl4/AtI2cV0hty8qNXZdpgVmoWU7bhBBrE9id4l+2SoV28aFOx3c/bnAQK/BrnijQoNWv5dBcTmSNN3Aivje/cki/McjbXlWFHd17He5WQNsVIdTygxyKxahkRsRivjkYv4odwNtQW/WqYMeQD6S5PPTUnLum1RF1hHZHIHOR+VUslwZQ7kgcnNlqaz/aAI2SNXpodxeTy5+fAZh26wX0DZ1Uh2T6PA60hSFNqDJa4fsDCfhffLEk8AhvdPCN7O/MzGm5CpsMgXU0g2rX4n0ivb7JJDO70wD24MNgul4CXdn8gYQvPvSGHgEowJrsSDjM7uu7L7C0ODlNjh1FUkObAp5idY7rOfX6uk=
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
