---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCh5sE5nJJnCqFXLpg3iynZeqzy0arcBzxUjRvhyQ8E0WiDRJkUZBm1vBmQfzPZGuhV/RTEi0D9u0vh43gdb8vxkiMjN2pWnpf6CCH+MMY8YLzgGsV96OuIQWUtvZmkNJ4Az07rh6n0ybZkH78QFM7VcE3uReN4AL6zmDia6SWwMimu/2T6eIed/aSHvqv9Y7EPWxaClh/zaFckpma4TJxTfdFg569Y/4/m4MxwT+hlq4FRHMeVbCQh/4AdXbNyta9Rjhb2YKOsDUiSfZK+hcLbUUshxADZ2EOo2FMX6/wgLf/bfz465glNbF9cNuzZ6de01I9QvvuERH6gA/Zeo2Zn9e0vile2/ONcdVeiDhUoC6klUKOCVdV/UJDRZZPu5q1mtWbsdym6ztcuSefV6KERxzhFlV/SGjTNIX9U6T15XlTU1vcBB/HduKQHB977sfoBQfOyX50E5uGZi+xqUxqpjvmGl8dK6Xd6Ao7IR+NAp5t9dA2VCwxiFLVpqV8p/GYu8JzNoi+47qi1TuHY4kLW+2jA1Bn8j406T7s1oXYEf4SHN/YM4hz9fU+UykjP0Unvp7Wuj6v8G2TnTAStUl2sRV9wKp+DhKj/mpwVErIHzUFk5dle3wJoncjBO/umLzL5++39ikGCdA9kBKXARMeBnv5AFsVIt3OIp6G5vFkzfRPxAz9d9EX7rJLg60yJrweKPG3kyr1lQVkoVlLnj3edvBXC8Vx87e2aJm+OB3e2+mnpfSP2G9xFGI1sAoi1SavuXHFoloHEF2UMcifSJWQDBm9n+pphGz8AhxtLP5wL/ru8QhD9pXhOdCyTsJpsBQ5lVAGMBBlGDP5LefZmY6tbsZmlyqfgdRrJvEZAXKHLLkBkg6b+T7S/8L/56Juos6OpiLokCXbVZ3hQ8kh/ur4X+e+mIRxqkROd9tKnPFabtq6yYKPdz+Jd
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
