---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCAEe2UYGxS3HFJm2J6xg1bLJ2hIJAzycZ0Wn94zeebG7n3O8G1weG1T+aNmRphCvYVCU/kBkuQcDZgGrn2eSqm1OigN72KS6CGbj4OVq3muXSDdu0WtXJecLtGIPab61Gmr7mjMsC0M0x2RosICBN36JiaPwabj1yj6mHz+vI+wgONLrVkezaieZjSzMqy6dSm/Mhxf2N3y2AWvwHW5SXIRfQc7w6DBTpL1bi3V1QL4SbBEFKAMjjtOKEI8x5iss10ZWyGr06VSWwSS/lq+bs+LeHrJQBSOyzNKq9tKePjtOpQfOJ6/DSEuzr+MQMpQECjrOF9k8V4qiILlwSjwoygSwdDpkR6Xft0TgFb5GSEctJcfxdigQkYpVoK9HPszA1fYbEvf4BiEtCe7I88uAxYwkDs91iK0UR/sd/xQz+a7c2pYTrG8C+1zgTZ4Fr+NG7gsMU9JA/MRPueaIRYGmKASJz8GEEHNmQ/ZDzYb9mw68G46lyBDrf6fujc+jqvDxWPJjOOiN6S56cVhUiZfuhXIfhtrOYBEKtJBQB1ta2opRo4Itk2C2vNWSTDCdILbU63mS1pUeV0kX9pLNh3yN4k1tf4cfe2PcM6yc7JMdqAWRKkeqYtHQgXpF4phIqcZwWbwt1+Xhwz/NJVIxczMX8f6X9bp+L9LloacIfxJWlFMZQOI0DOA1o8VwOEiZSSY8qgpn5gC1TMch0jJlf551lYKCto50YJn7KeKGNQnxYmK2zSulncaB6XYuU1tmh3bHBnJT4hrMycRNirSF8p9NcRAAm0SShimNuS90HFYoT8FsVMdibdX22RcRhkKgpz10jyUmTIRvxRhgazkW2MUGaP6Cmx8hNGR00R2rEeEJeBe216/hhvjxEZCjcZhfzH012bHZOCgrPllbOW2FT5pBYrEJ4Bb0PHM8Dv2ijl0q+IZaxMTkwJnSeB
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
