---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgA4iQfyOjBXnOoOuDlvQr8z1LYqULnMHE5k+/7f1yVjRYaY3OS5tXn7+nccbl6f2TapazAD6wzYioEg+caBfuDqWIaHwpZ25voJkQSZ6Ws8KOgOzqvnLYD1h4r7HMu5bgPtS88RJ0qVARZvhYDXl56cHgRm+J3fV+LcFX04siVru+Q3rUoOPgJvzBFoI7g35vS3c1kTyQFLKprgsoHPDZD70t4s7JLc0YRjIdktS6RO7IJvUz0bniZePTL2HFvgEsto9sgEaEjANsxA+jsQHJQInnlorf+BB6w1RvdTB478m2nyPuyiH8I205Pct8q5MXaJqv0uxrbJdlDSb3i+lzN1WnIWjlV+5/PZ5TInFqIusidiZ6YHPV0nG2MmDJ4DvjXkkCF4TpcXwulOhoKvS5x1HkREntnjJ2WTC61EROVkY/BIQha7j+L4hGHhgeiGLSUN1bH2qz49Gxxo4JPg76oKbwLaEYH9HEKT3VBU7YuQVwJLvAiPh7WjrFLutLlCLwNYxZX6QNnb/uCEzfQ+oKLvtjSdpPqIxokskQrk1qn0IEsKYD8+csFBfVb+bkvcp4n1ZiakIamx9qGa8k9/t8XJ1A2lT+gYTM6X14I9qb/HHMdQflEDA1Nt5LrsoaNtdVh2PGgeL5Kq5AG8qUgLT3d74NfXrEVFGZ/YgctVKhZmx2XrLZFzepLOUs9lUhXfLLTD0SXn/YyoAahCk7TGZOPhja0f2D9V4FSsRifc0R7PNR5BJ2AuqLvwkcysP9KYIZ7BJK1newqDDouFuIR3S6lwEcdFgA2w9jKU1vqy1kT4cSI5YZUO4J5h+tYEEEIhnWXXVAg6+fhDfLI/EZtwV21ueuN8YhGO8VFj7Qa5XEvxHOR38P4JtutKf8lLOT/UYHpgzPjMjOaiXMG5m4ClquvtVeRDOaoc7aNXG1zuxb4Hbtjhw3j5shij
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
