---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCHjqynrl94i3RUv35VmC6ee22W2TUGjXqcPJjhanm4vYIYhG4Ej6DfMQLhhfNfhN6V4d7aXHH9QHo6soo4m+SR/QSo10KYBefQsHVh6S3zgFjTHc9KqbZz5qWr4HHPTmZDOTyEvRCRAEV1d06lNlOdxvFNGtEgNxXcxVvv3hv/qnPlosFjJkjmIqlPSlktUP14u36ylEJmkI//CkRc+bNavys8uc9P4nMZZBiIRT8sFWuAdWRQ/mkNcZjc3o7LixLfu8U+FVHvLa2c8mXn3hGfW4PYen97Zkrh5Bn+dE9DRkm1znF3W5KFZYb2YNphX0/zZSBcAP04hp/cNXf+S+YF793Jk1etjcY7DcJMr5az82qMpDb8sJA3P5uxH2i6omp+2K+020qiaJo3eIl2DMLGzy3w7B6jJZ714JugMP2TbKUSdaULuym+l0EN1t0ChmZ3XXeM9Pr0SY5ws7oqOe4DtEZRYcRQ4TyYNlRseHnuesGShyfa2nm9N7CzgVajbVC1uEG4dnwdrUecJAUTlqMFLLULZJ1rbYuewdMURhASRRA3yZwJpUmEw86zWYFaMQ39uDsZ/taFxiQVl0N7KSzXVCdbF+UjEbCdklVO4Q+qYuPwQkaZmX8yvFllpakShl/jSUyHffV2N3KY3TRU5uKamYeXNCeTI2vhmiDRJdfliGOh38lSUrKXFZD0zcwK5cVipRDByw7VaIvCyDcXzPOD
  template:
    metadata:
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
