---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAgoVTxTVEXpc+y2xWSTdxzPKuSxheXIckdBaKWUle3yLnCfLkB8COgFMDS23vB6U15G1yHMDCcNFaySV8SQY7Le7cAeugqfAiNNWfrf9AhPBUwFs1+skdMq6fq5fetZwUzbKThZ20nebBb+vprPfXrEEJ+w0+rhwR2aXJ5Nrld8yGX8Y0Gl/fkb+bhMXQaICTwTFkwRzuT5vedzdBBNR1YS/3tfGBE2J/J0Mxa+xy/wF6GHkFGxgKhJHd8o+DigDVkNJz0jTqnE1Ql1Il9OadauMX1Ogamb0iFkhlgZYyg/sqfKBn5jZxBCBdbRBejY0mzJ0NzpcFnp1rmm+Qm/sh5MDpma3upspl4/psHT/A+hN1+4ZpHac1lHbaSkbmnv63+SR92uSRx9Ts6LLKpqF3jOCNt+tBiDWSPmqAZ/4bHrzGUllIdYBbd45v6x9XOjWEbLBvbCiOdJlNkkAb5jAMxSiuKZj+3ojXFN+SXy3OthKoQY62UEmfBN8z1MKlsDLFZ8i3eAGAOliy7Yupts7fwETcq1fMoGiYtqNLLj/sdostHCGXDwmvmC3kAz9iY62YGHZSVsdPeDFAZslRxCVFrXQSHW2L1AXm7tnfvUNDptoDDVgobcaCR5XKgZ8EWqbhM91C+8j01Mb3taDkl68reAUncmGBve/hlPIQtSs71B8Wcf3PBuQdMuny8HdwTnou+5sUmho7IVghkI3Thrikg
  template:
    metadata:
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
