---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-secret
  namespace: navidrome
spec:
  encryptedData:
    password: AgAeuE2o7rXSx8ZCgV88i6BIv9sP4o57Gz6QPOahFo9s7g/2R6zUDVh/0vJfm1rt2Wlu1Ibnkw09Nw5rlXEkLwQ4cBXydoagRN4yelQo3lFchnJKXPUTqHvl3sfqo8IA4vhfgJJUrIjg8LpSGV3mlsimEv2OqxNujYviF5X7PzPHYhbTbgg0v4WeiFXu9oKzFDLDGKMt9J3YD9S158y8pGwU/DPQvkGs2o3nbEIzrTi5KrMAFfNDrk7MWvYFi+k7n3VUewQ+R4onpdIpWCixkqYE3/V9kcXm3P+dEFdXmPQezNRG7Pb8nDM4rCq3Zv00q1zgF/mg38miHFg/SKuXrI2+mRZfUYyeHFHhykIyQU6JvrqaFkhAFft7aO0pek4HAw7wZ6ZRZXUsAc8c/bZAWhjgvPQbhlBWDMXpT8dcSWs0yC/yrFKGGLK142hpJr3rB2hiJlPPzmzh9d1Qyq16oRQFN+04OXSbXOh/LjAMQIK/QFEOICc8eNz0G7MFl7Kr6DQCvSoT0itlIkEYU3sUDmj2+o1ZoMftQS7HmKSwGhgFilLyMXRSebjt7QzHs9lesRrTCDT5XYH/iqHSd8qKxbJ6ZrkKxUotqtbiIdxN0/vn5cgV7yRjAggftfKCE3KnpajjyTM6/oo7MftKmYoHeTI9qa+kM4bxtDmAzY8kL3W5/ZAhj90Sm6EFWboeNK+UYp56KQe6yQKV0fUsLs8SY25vhFRg8w==
    username: AgB4tHrs68sTu8nwsbrpw33UGGCIz5Zl33gCyzyJraNHTxWKcM/0m/K0yeVNRIBnidEzU5I2FDb0RNRoAjoEsQl8paqbAjp6itGkZ0c+yDmAjaVUM/5Sa2O/TClAdIwWtK+K9Hqsc1LCsdYvjs48TMnLVgQVNazWwSNIGV3dJXbokGn5+47LB2REms8CX5I4nPopVxjPOnndwaLjYimTJNRoPPKWueFXk9k72OgAWl7aDzOHu7D9R2k5flNnLkhGLn2wsTu1ZoyWr+DS2L+kByanmIR2ECPVosHardT/E0zcQwhqlvwAn39EscuNHbCvYEPtzCBzX1jAclWjj2recr5h8VCguuP3LrGPuMpy4bTS/sHfp44VXqxfe2UhJVO7jNo+tRZH+fh6feyZNA6K2bUWTVNeD9DVdvTJ2m0GeL0ZkepVtdxRJu/GbZJ6Tq49PiLUC9Rng6fmlotP9Pt1D1XM74o5eeTEXW9Vludyg42bQ1/6uoLgmHL3spgA+HTkvYXDdlFjzJGRX2g+QdIdUG1NuYWWfYEPn8McewrN8vF1lcfW7liUrlkEkaYUIcnICos33nYacaKP6JyiVuXWIniqqluvaSf20lBqQO04j36Jtq7p49/+zbyEWDyIik86mPKykp02uhBd8MHZRkinPWe1AmxS01Cra7BaRz3Eo8jSva2k8qYcPw0NJIaaX2yrBxoOLP0Hung83YG4gaOUDzwcWjRuGg==
  template:
    metadata:
      name: navidrome-secret
      namespace: navidrome
    type: Opaque
