---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-secret
  namespace: navidrome
spec:
  encryptedData:
    password: AgAVautc/YB1j1bWdUmSChUk9XLAxknA3pQJMcqEF2dnMOeVpv3lttL4PJ/YgOq1x3iYes0QMJFCVw1QUuncYfg793exdL14QPFzJSzFaVmVFDEvKQpda8zkVgQdxLIgQm7N9ngJw9f6m18/+vKgF8bIyKRLRCsiH2IymgoV9P7sldM/GlXoR27ycw45T+d7gEXszf8cwQukBv9AZ4R4mJkYTJmN2ulM5GAmQY5YyIAIObsV1YyQrq3N+45uZt32+T9wwifz3svuU6JO9X7oG+zum2aGOkQgIE95UOQAkRACaQuakLF/NjXBoiPWx9DwKdib3tj6kkDh0MrObeuGtQ4rqnJjQOCsckhM9BwcETipkw9oifSxIwk9rLeQYus0lMVTe30bMO51K21K2QYJAyDViukkpcgHKFnYictxFg1w9IcqXRXLvrXU2jTovrL+Gf1ruwfggNzWq0a4Ldoe5275x5zAwv1kfIPjnrqdboN9G9o+5eyOHzUVuXSCCm8KhxezgKeV9SUTZV7K4NKLD68w5OPRCoy6vx/b92ASDYgJS6XOBSFGcHjHeAV53N5zT50nhnFYuy6fOitxAoaDnQJ7C+M44BoONYrwEEd8TsCCGXl19Vekq9MAo/KpCYf99AJ33Du9hCFZFemiYPPji6Ekr/6S2B0jcXLMSA988u0vogMzq2isyqCvRdByWknvMjlocT3yBkq4u50covEyyAbv51iLNQ==
    username: AgA8gTbQR3p1C0k3OCTLe+xhMdx5wrukKKOc6Tio6gsMbX6eOj2oBxlCk6Di/LMiKlVJlp8rfdi7QLfTTESwkfjt1UO7Uoi3M1NWlzXaM64NSBrMlNVW2FJV6qQ1EhufL0eVnh/l+ISEWyk+bT3mDyHp8viJCI2eO29uNDcw2ipE8CXSjICxNyLnA9SENpq88zfU5+N271D/PUqr0mnsKC/TkvLa2ZPRyGoTOR7QBu+0wWslAGn6gIXkiUjsgTScIqcjD5dZlpoknA5cmsfTDJp/AyaWWM2/KlmR/4GfgMASS23+UCi8xXdwevi3J8kXpvveqdFbD9T5K7b3pSpnKP1MOz1NmfaOaTI42xHF7ivLD3/BreOnY4LiRvSAsrTrCTZ1Qxv/iBFAQJzEZPVqK5zRP47EV5O2qRDZ7sdpvTtbImNTaKe2E9PWpJY6WuofeiUjmd5XK9DbmpSOKZX0UeT1ovyyfcv2EdHOJBiWiIfTrzYJqPqyujDgxN3ghebfCavc9nBFngjDKOgzX6wNctDggJJkQVA/jff8wUuvoKQKrVDfS8nOq9aFv73iZ0QIImKL2hG0IVnMOlDMhHnSvkAaeadl/SvGQmlRAmygzgeM2nMJoVmWVxt5/qXfA6WvRU0kBVociAnnWMM72qbMWZSJBkSImrVpPb20udq5axEzI/OtTzJui+rUjnQoqkpkyfjZ094gnaZuyU7Fy0hB0va5/1ystg==
  template:
    metadata:
      name: navidrome-secret
      namespace: navidrome
    type: Opaque
