apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: navidrome-data-cephfs-storage-class
  namespace: navidrome
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
