apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-proxy-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: minecraft-proxy-cephfs-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server1-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: minecraft-server1-cephfs-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backup1-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 275Gi
  storageClassName: minecraft-backup1-cephfs-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server2-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: minecraft-server2-cephfs-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backup2-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 275Gi
  storageClassName: minecraft-backup2-cephfs-storage-class
