apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music-pv
  namespace: navidrome
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: navidrome-music-pv
    volumeAttributes:
      source: "//192.168.11.42/music"
    nodeStageSecretRef:
      name: navidrome-secret
      namespace: navidrome
  mountOptions:
    - ro
